pipelines:
  gocd-rpi-unicorn-hat-monitor:
    group: defaultGroup
    locking: off
    materials:
      main_repo:
        git: https://github.com/d-led/gocd-rpi-unicorn-hat-monitor.git
        branch: master
    stages:
      - test:
          clean_workspace: false
          jobs:
            unit:
              tasks:
               - exec:
                   command: python
                   arguments:
                    - FakeHat.py
               - exec:
                   command: python
                   arguments:
                    - matrix.py
